@startuml

Class Project {
    + tasks: Task[0..*]
    + team: Team
}

Class Task {
    + name: String
    + description: String
    + duration: DateTime
    + subTasks: Task[0..*]
    + parentTask: Task
    + project: Project
    + start: Date
    + end: Date
    + completed: Boolean
    + predecessors: Task[0..*]
    + succcessors: Task[0..*]

    - assignedMembers: Member[0..*]
    - requiredSkills: Skills[0..*]
    
    + getRequiredSkills(): Skills[0..*]
    + isMemberQualified(member: Member): Boolean
    + qualificationDateForMember(member: Member): Date
    + isAssigned(): Boolean
    + tryAssignMember(member: Member): void
    + forceAssignMember(member: Member): void
    + getAssignedMembers(): Member[0..*]
    + isLate(): Boolean
}

Class Skill {
    + name: String
    + level: Integer     
}

Class UpcomingSkill extends Skill {
    + acquisitionDate: Date
    + isAcquired(): Boolean
}

Class Member {
    + name: String
    + description: String
    + color: Color
    + availableWeeklyHours: Double
    + availableDailyHours: Double 
    + tasks: Task[0..*]
    + teams: Team[0..*]    
    + skills: Skills[0..*]
    + upcomingSkills: UpcomingSkill[0..*]
    
    + refreshSkills(): void
    + getCurrentSkills(): Skills[0..*]
    + addSkill(skill: Skill): void
    + addUpcomingSkill(skill: UpcomingSkill): void
}

Class Team {
    + name: String
    + color: Color
    + description: String
    + members: Member[0..*]
}

Class Model {
    + projects: Project[0..*]
    + teams: Team[0..*]
    + members: Member[0..*]
    + availableSkills: String[0..*]

    + asProjectFile(): Object
    + fromProjectFile(file: Object): Model
    + deleteSkill(name: String): void
    + addSkill(name: String): void

}

Task *-- Task : 0..*
Task *--o Member: 0..*
Task --> Project
Project *-- Tasks: 0..*
Project *-- team: 1
Task o-- Skill: 0..*
Member o-- Skill: 0..*
Member o-- UpcomingSkill: 0..*
Team o-- Member: 0..*
Model o-- Team: 0..*
Model o-- Member: 0..*
Model o-- Project: 0..*

@enduml
